site_name: Computational Statistics
nav:
    - Home: index.md
    - INSTALL: INSTALL.md
    - LANGUAGES: LANGUAGES.md
    - PARALLEL: PARALLEL.md
    - REPRODUCE: REPRODUCE.md
    - SYSTEM: SYSTEMS.md
    - WEB: WEB.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
