site_name: Computational Statistics
repo_url: https://github.com/jinghuazhao/Computational-Statistics
edit_uri: ""
nav:
    - "": README.md
    - INSTALL: INSTALL.md
    - LANGUAGES: LANGUAGES.md
    - PARALLEL: PARALLEL.md
    - REPRODUCE: REPRODUCE.md
    - SYSTEMS: SYSTEMS.md
    - WEB:
      - AI.md
      - Computing:
        - "Computing resources": Computing.md
        - Utilties: Utilities.md
      - Internet:
        - mythic-beasts: src/mythic-beasts.md
        - Flask: Flask/README.md
        - plumber: plumber.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
