site_name: Computational Statistics
repo_url: https://github.com/jinghuazhao/Computational-Statistics
edit_uri: ""
nav:
    - "": README.md
    - INSTALL: INSTALL.md
    - LANGUAGES: LANGUAGES.md
    - PARALLEL: PARALLEL.md
    - REPRODUCE: REPRODUCE.md
    - SYSTEMS: SYSTEMS.md
    - WEB:
      - "Utilties": Utitlies.md
      - "Flask": Flask/README.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
