site_name: Computational Statistics
repo_url: https://github.com/jinghuazhao/Computational-Statistics
edit_uri: ""
nav:
    - "": README.md
    - AI.md
    - INSTALL: INSTALL.md
    - LANGUAGES: LANGUAGES.md
    - PARALLEL: PARALLEL.md
    - REPRODUCE: REPRODUCE.md
    - SYSTEMS: SYSTEMS.md
    - WEB:
      - Computing:
        - "Computing resources": Web/Computing.md
        - Utilties: Web/Utilities.md
      - Internet:
        - Flask: Web/Flask/README.md
        - mythic-beasts: Web/mythic-beasts.md
        - plumber: Web/plumber.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
